//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blogDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentId { get; set; }
        public string CommentContent { get; set; }
        public System.DateTime CommentDateTime { get; set; }
        public int PostId { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
